var definedLevels = [
{
	width: 252,
	height: 15,
	id: 0,
	background: 1,
	data:
	[
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'mario' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'materi_box_1' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'mushroombox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'materi_box_2' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , 'ballmonster' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'checkpoint_1' , 'grass_top' , 'soil'],
	['' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'materi_box_3' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'materi_box_4' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'starbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'checkpoint_2' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'materi_box_5' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top' , 'planted_soil_left' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'materi_box_6' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_left' , 'pipe_left' , 'pipe_left_grass' , 'pipe_left_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right_grass' , 'pipe_right_soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'stone' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'stone' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'multiple_coinbox' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top_right_rounded' , 'soil_right'],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	[ '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'grass_top_left_rounded' , 'soil_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , 'coin' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil']
	]
}
	,
{
	width: 220,
	height: 15,
	id: 1,
	background: 2,
	data:
	[
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','mario','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','coinbox','','','','','grass_top','soil'],
	['','','','','','','','','mushroombox','','','','','grass_top','soil'],
	['','','','','','','','','coinbox','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','ballmonster','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','pipeplant','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','','','','','','pipe_top_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','soal_box_1','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_right','soil'],
	['','','','','','','','','soal_box_2','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_top_left_corner','soil','soil'],
	['','','','','','','','','bush_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_right','grass_top','soil','planted_soil_left','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_right','soil','soil','soil'],
	['','','','','','','','','greenturtle','grass_top_right','grass_right','grass_right','grass_right','grass_right','grass_right'],
	['','','','','','','','','','brown_block','','','','',''],
	['','','','','','','','','coin','brown_block','','','','',''],
	['','','','','','','','','','brown_block','','','','',''],
	['','','','','','','','','','','brown_block','','','',''],
	['','','','','','','','','','coin','brown_block','','','',''],
	['','','','','','','','','','','brown_block','','','',''],
	['','','','','','','','','','','','brown_block','','',''],
	['','','','','','','','','','','coin','brown_block','','',''],
	['','','','','','','','','','','','brown_block','','',''],
	['','','','','','','','','','','','','brown_block','',''],
	['','','','','','','','','','','','coin','brown_block','',''],
	['','','','','','','','','','','','','brown_block','',''],
	['','','','','','','','','','','','checkpoint_1','grass_top_left','grass_left','grass_left'],
	['','','','','','','','','','','','bush_left','grass_top','soil','soil'],
	['','','','','','','','','soal_box_3','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','brown_block','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','mushroombox','','','bush_right','grass_top','soil','soil'],
	['','','','','','','','','brown_block','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','coinbox','','','','grass_top','soil','planted_soil_middle'],
	['','','','','','','','','','','','spikedturtle','grass_top','soil','planted_soil_right'],
	['','','','','','','','','','','','','grass_top_right','grass_right','grass_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','grass_top_left','grass_left','grass_left'],
	['','','','','','','','','','','','','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','planted_soil_right','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','starbox','','','bush_left','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_right','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_middle'],
	['','','','','','','','','soal_box_4','','','greenturtle','grass_top','soil','planted_soil_right'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','spikedturtle','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_left','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle_right','grass_top','soil','soil'],
	['','','','','','','','','','','','bush_middle_left','grass_top','soil','soil'],
	['','','','','','','','','coinbox','','','bush_right','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','pipeplant','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_left','soil'],
	['','','','','','','','','','','','','grass_top','planted_soil_middle','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_top_left_corner','planted_soil_middle','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','planted_soil_right','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','spikedturtle','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_right','grass_right','grass_right','grass_right','grass_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top_left','grass_left','grass_left','grass_left'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','soil','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','planted_soil_left','soil'],
	['','','','','','coin','coin','','ballmonster','brown_block','brown_block','grass_top','soil','planted_soil_middle','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','planted_soil_right','soil'],
	['','','','','','coin','coin','','','brown_block','brown_block','grass_top','soil','soil','soil'],
	['','','','','','','','','','','brown_block','grass_top_right','grass_top_right_corner','soil','soil'],
	['','','','','','','','','','','','brown_block','grass_top_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','brown_block','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','greenturtle','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','grass_top_left_rounded','soil_left'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','soal_box_5','coin','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','coin','coin','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','mushroombox','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right','grass_top_right_corner'],
	['','','','','','','','','','','','','','staticplant','grass_top'],
	['','','','','','','','','','','','','','staticplant','grass_top'],
	['','','','','','','','','','','','','','grass_top_left','grass_top_left_corner'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle'],
	['','','','','','','','','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','coin','coin','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil'],
	['','','','','','','coin','coin','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','ballmonster','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_left','grass_top_left_corner','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','coinbox','','','ballmonster','grass_top','soil','planted_soil_left','soil','soil','soil'],
	['','','','','','soal_box_6','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','coinbox','','','','grass_top','soil','planted_soil_middle','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','planted_soil_right','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil','pipe_left_soil','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','pipe_top_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil','pipe_right_soil','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_right','grass_right','grass_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','brown_block','brown_block','brown_block','','grass_top','planted_soil_right'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','','compiler_box_1','coin','','grass_top','soil'],
	['','','','','','','','','','','mushroombox','','coin','grass_top','soil'],
	['','','','','','','','','','','soal_box_7','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','','coin','','grass_top','soil'],
	['','','','','','','','','','brown_block','coin','','coin','grass_top','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','brown_block','grass_top','soil'],
	['','','','','','','','','','grass_top_left','grass_left','grass_left','grass_left','grass_top_left_corner','soil'],
	['','','','','','','','','bush_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_right','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_left','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','bush_middle_right','grass_top','soil','soil','planted_soil_left','soil','soil'],
	['','','','','','','','','bush_right','grass_top','soil','soil','planted_soil_middle','soil','soil'],
	['','','','','','','','','greenturtle','grass_top','soil','soil','planted_soil_middle','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','planted_soil_right','soil','soil'],
	['','','','','','','','','','grass_top','soil','soil','soil','soil','soil'],
	['','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil','soil'],
	['','','','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil'],
	['','','','','','','','','','','','','grass_top_right','grass_top_right_corner','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','spikedturtle','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','grass_top_left_rounded','soil_left'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','bush_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_right','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle','grass_top','soil'],
	['','','','','','','','','','','','','bush_middle_left','grass_top','soil'],
	['','','','','','','','','','','','','bush_right','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_middle']
	]
}
	,
{
	width: 220,
	height: 15,
	id: 2,
	background: 3,
	data:
	[
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'mario' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left_rounded' , 'soil_left' , 'soil_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'grass_top'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'planted_soil_left' , 'soil' , 'grass_top_right_rounded_soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'materi_box_loop_1' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_right' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , 'coin' , 'coin' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'coin' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'planted_soil_left' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , '' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'coin' , 'grass_top' , 'planted_soil_middle' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'coin' , '' , '' , '' , '' , 'coin' , 'grass_top' , 'planted_soil_right' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'coin' , 'coin' , 'coin' , 'coin' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_left'],
	['' , '' , '' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle'],
	['' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_right'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner' , 'planted_soil_right' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , 'brown_block' , 'coin' , 'brown_block' , '' , 'multiple_coinbox' , '' , 'materi_box_loop_2' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'brown_block' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'coin' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'coin' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'mushroombox' , '' , '' , '' , 'coinbox' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner' , 'soil'],
	['' , '' , '' , 'coinbox' , '' , '' , '' , 'coinbox' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , '' , '' , 'pipe_top_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'ballmonster' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , 'brown_block' , 'brown_block' , 'brown_block' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , 'checkpoint_1' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , 'materi_box_loop_3' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_left' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle' , 'grass_top' , 'soil' , 'soil' , 'planted_soil_right' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle_right' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_middle' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_left' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , 'bush_right' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_middle' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'planted_soil_right' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , 'coin' , 'coin' , '' , '' , '' , 'grass_top' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil' , 'soil'],
	['' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right' , 'grass_right'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left' , 'grass_top_left_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'spikedturtle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top' , 'soil'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right' , 'grass_top_right_corner'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'materi_box_loop_4' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipeplant' , 'pipe_top_left' , 'pipe_left' , 'pipe_left' , 'pipe_left_grass'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'pipe_top_right' , 'pipe_right' , 'pipe_right' , 'pipe_right_grass'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'coinbox' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , 'materi_box_loop_5' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'greenturtle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_right'],
	['' , '' , '' , '' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , ''],
	['' , '' , 'coin' , 'coin' , '' , '' , 'brown_block' , '' , '' , '' , '' , '' , '' , '' , 'grass_top_left'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle_left' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_middle' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'bush_right' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top'],
	['' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'grass_top']
	]
}
	,
{
	width: 194,
	height: 15,
	id: 3,
	background: 8,
	data:
	[
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','mario','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','planted_soil_left'],
	['','','','','','','','','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','coinbox','','','','grass_top','soil'],
	['','','','','','','','','','coinbox','','','ballmonster','grass_top','soil'],
	['','','','','','soal_box_loop_1','','','','coinbox','','','','grass_top','soil'],
	['','','','','','coinbox','','','','coinbox','','','','grass_top','soil'],
	['','','','','','coinbox','','','','coinbox','','','','grass_top','soil'],
	['','','','','','coinbox','','','','coinbox','','','','grass_top','soil'],
	['','','','','','coinbox','','','','coinbox','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','grass_top_left_rounded','soil_left','soil_left','soil_left','soil_left'],
	['','','','','','','','','','','grass_top','soil','stone','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','soal_box_loop_2','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','greenturtle','grass_top','soil','soil','soil','soil'],
	['','','','','','mushroombox','','','','','grass_top','soil','soil','stone','soil'],
	['','','','','','','','','','stone','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','stone','stone','soil_right','soil_right','soil_right','soil_right'],
	['','','','','','','','','','stone','stone','','','',''],
	['','','','','','','','','','','stone','','','',''],
	['','','','','','','','','','','stone','','','',''],
	['','','','','','','','','','stone','stone','brown_block','brown_block','brown_block','brown_block'],
	['','','','','','','','','','stone','','','','',''],
	['','','','','','','','','','stone','','','','',''],
	['','','','','','','','','ballmonster','stone','','','','',''],
	['','','','','','','','','','stone','stone','','','',''],
	['','','','','','','','','','stone','stone','','','',''],
	['','','','','','','','','','','stone','brown_block','brown_block','brown_block','grass_top_left_rounded'],
	['','','','','','','','','','','stone','stone','brown_block','brown_block','grass_top_right_rounded'],
	['','','','','','','','','','','stone','stone','','',''],
	['','','','','','','','','','','','stone','','',''],
	['','','','','','','multiple_coinbox','','','','','stone','','',''],
	['','','','','','','','','','','','stone','','',''],
	['','','','','','','','','','','stone','stone','brown_block','brown_block','brown_block'],
	['','','','','','','','','','','stone','stone','brown_block','brown_block','brown_block'],
	['','','','','','','','','','','stone','','','',''],
	['','','','','','','','','','stone','stone','','','',''],
	['','','','','','','','','','stone','','','','',''],
	['','','','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','brown_block'],
	['','','','soal_box_loop_3','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','ballmonster','stone','brown_block','brown_block','brown_block','brown_block','grass_top_left_rounded','soil_left'],
	['','','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','grass_top_right_rounded','soil_right'],
	['','','','','','','','','stone','','','','','',''],
	['','','','','','','','','stone','','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','brown_block','brown_block','brown_block','brown_block','brown_block'],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','brown_block','brown_block','brown_block','brown_block','grass_top_left_rounded'],
	['','','','','','','','','stone','stone','brown_block','brown_block','brown_block','brown_block','grass_top_right_rounded'],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','stone','stone','','','','','',''],
	['','','','','','','','stone','stone','','','','','',''],
	['','','','','','','','stone','stone','','','','','grass_top_left_rounded','soil_left'],
	['','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','brown_block','grass_top','soil'],
	['','','coinbox','','','','','stone','','','','','','grass_top','soil'],
	['','','brown_block','','','','','stone','','','','','','grass_top','soil'],
	['','','coinbox','','','','','stone','','','','','','grass_top','soil'],
	['','','brown_block','','soal_box_loop_4','','','stone','','','','','','grass_top','soil'],
	['','','coinbox','','','','','stone','','','','','','grass_top','soil'],
	['','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','brown_block','grass_top','soil'],
	['','','','','','','','stone','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','stone','','','','','','',''],
	['','','','','','','','stone','stone','','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','ballmonster','stone','stone','brown_block','brown_block','brown_block','brown_block','brown_block'],
	['','','','','','','','','stone','stone','brown_block','brown_block','brown_block','brown_block','brown_block'],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','stone','','','','','',''],
	['','','','','','','','','stone','','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','','stone','','','','',''],
	['','','','','','','','','','stone','grass_top_left_rounded','soil_left','soil_left','soil_left','soil_left'],
	['','','','','','','','','','stone','grass_top','stone','soil','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','soal_box_loop_5','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','greenturtle','grass_top','soil','stone','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top','soil','soil','soil','soil'],
	['','','','','','','','','','','grass_top_right','grass_top_right_corner','soil','soil','soil'],
	['','','','','','','','','','','','grass_top_right','grass_right','grass_top_right_corner','planted_soil_left'],
	['','','','','','','','stone','','','','','','grass_top','planted_soil_right'],
	['','','','','','','','stone','','','','','','grass_top','soil'],
	['','','','','','','','stone','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','stone','','','','','','','grass_top','soil'],
	['','coinbox','','','','','stone','','','','','','spikedturtle','grass_top','soil'],
	['','','','','','','stone','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','','','','','','','grass_top','soil'],
	['','','','','','','','stone','','','','','','grass_top_right_rounded','soil_right'],
	['','','','','','','','stone','','','','','','',''],
	['','','','','','','','stone','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','grass_top_left_rounded','soil_left','soil_left','soil_left','soil_left','soil_left','soil_left'],
	['','','','','','','','','grass_top','planted_soil_left','soil','soil','soil','soil','soil'],
	['','','','','','','','','grass_top','planted_soil_right','soil','soil','soil','stone','soil'],
	['','','','','','','','','grass_top','soil','soil','soil','soil','soil','soil'],
	['','','','','','','','ballmonster','grass_top','soil','soil','soil','soil','soil','soil'],
	['','','','','','','','','grass_top','soil','soil','stone','soil','soil','soil'],
	['','','','','','','','','grass_top','soil','soil','soil','soil','soil','soil'],
	['','','','','','','','','grass_top','soil','soil','soil','soil','soil','soil'],
	['','','','','','','','stone','grass_top_right_rounded','soil_right','soil_right','soil_right','soil_right','soil_right','soil_right'],
	['','','','','','','','stone','stone','','','','','',''],
	['','','','','','','','stone','stone','','','','','',''],
	['','','','','','','','','stone','stone','','','','',''],
	['','','','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','grass_top_left_rounded'],
	['','','','','','','','','','stone','brown_block','brown_block','brown_block','brown_block','grass_top_right_rounded'],
	['','','','','','','','','','stone','stone','','','',''],
	['','','','','','','','','','','stone','','','',''],
	['','','','','','','','','','','stone','','','',''],
	['','','','','','','','','','','stone','stone','','',''],
	['','','','','','','','','','','stone','stone','','',''],
	['','','','','','','','','','','','stone','brown_block','brown_block','brown_block'],
	['','','','','','','','','','','','stone','brown_block','brown_block','brown_block'],
	['','','','','','','','','','','','stone','','',''],
	['','','','','','','','','','','','stone','','',''],
	['','','','','','','','','','','','grass_top_left_rounded','soil_left','soil_left','soil_left'],
	['','','','','','','','','','','','grass_top','soil','stone','soil'],
	['','','','','','','','','','','','grass_top','soil','soil','soil'],
	['','','','','','','','','','','','grass_top','soil','soil','soil'],
	['','','','','','','','','','','','grass_top','soil','soil','soil'],
	['','','','','','','','','','','','grass_top','stone','soil','soil'],
	['','','','','','','','','','','','grass_top','soil','soil','soil'],
	['','','','','coin','coin','','','pipeplant','pipe_top_left','pipe_left','pipe_left_grass','pipe_left_soil','pipe_left_soil','pipe_left_soil'],
	['','','','','coin','coin','','','','pipe_top_right','pipe_right','pipe_right','pipe_right_grass','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_right'],
	['','','','','soal_box_loop_6','','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','','','','','brown_block','brown_block','brown_block','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','stone','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','stone','','','grass_top','soil','soil'],
	['','','','','','','','','','stone','','pipeplant','pipe_top_left','pipe_left_soil','pipe_left_soil'],
	['','','','','','','','','','stone','','','pipe_top_right','pipe_right_soil','pipe_right_soil'],
	['','','','','','','','','','stone','','','grass_top','soil','soil'],
	['','','','','','','','','','stone','','','grass_top','soil','soil'],
	['','','','','','','','','','stone','','','grass_top','soil','soil'],
	['','','','','','','','','','soal_box_loop_7','','','grass_top','soil','soil'],
	['','','','','','','','','','stone','stone','stone','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','stone','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','compiler_box_1','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_left'],
	['','','','','','','','','','','','','grass_top','soil','planted_soil_right'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top_right_rounded','soil_right','soil_right'],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','','',''],
	['','','','','','','','','','','','','grass_top_left_rounded','soil_left','soil_left'],
	['','','','','','','','','','','','','grass_top','stone','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','ballmonster','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil'],
	['','','','','','','','','','','','','grass_top','soil','soil']
	]
}
	,

];

var branchLevels = definedLevels.slice(0, 2);
var loopLevels = definedLevels.slice(2, 4);